/**
 * Health Check Thresholds
 */
export const HEALTH_THRESHOLDS = {
  MEMORY_DEGRADED_PCT: 85,
  MEMORY_UNHEALTHY_PCT: 95,
  CPU_DEGRADED_FACTOR: 0.7,
  CPU_UNHEALTHY_FACTOR: 0.9,
  DB_DEGRADED_MS: 1000,
  REDIS_DEGRADED_MS: 500,
} as const;

/**
 * Headless Browser Detection Scores
 */
export const HEADLESS_SCORES = {
  THRESHOLD: 50,
  UA_HEADLESS_INDICATOR: 100,
  DEVTOOLS_PROTOCOL: 90,
  AUTOMATION_TOOL: 80,
  MISSING_HEADER: 12,
  SUSPICIOUS_ACCEPT_LANG: 15,
  MISSING_SEC_CH_UA: 25,
  CONNECTION_CLOSE: 10,
  GENERIC_ACCEPT: 10,
  MISSING_SEC_FETCH: 20,
} as const;
